#!/usr/bin/env bash
mkdir -p '@types'
touch '@types/.keep'
mkdir -p 'actions'
touch 'actions/.keep'
mkdir -p 'addon'
touch 'addon/.keep'
mkdir -p 'addons'
touch 'addons/.keep'
mkdir -p 'admin'
touch 'admin/.keep'
mkdir -p 'admins'
touch 'admins/.keep'
mkdir -p 'android'
touch 'android/.keep'
mkdir -p 'angular'
touch 'angular/.keep'
mkdir -p 'anim'
touch 'anim/.keep'
mkdir -p 'animated'
touch 'animated/.keep'
mkdir -p 'animation'
touch 'animation/.keep'
mkdir -p 'animations'
touch 'animations/.keep'
mkdir -p 'anims'
touch 'anims/.keep'
mkdir -p 'ansible'
touch 'ansible/.keep'
mkdir -p 'api'
touch 'api/.keep'
mkdir -p 'apis'
touch 'apis/.keep'
mkdir -p 'apollo-cache'
touch 'apollo-cache/.keep'
mkdir -p 'apollo-client'
touch 'apollo-client/.keep'
mkdir -p 'apollo-config'
touch 'apollo-config/.keep'
mkdir -p 'apollo'
touch 'apollo/.keep'
mkdir -p 'app'
touch 'app/.keep'
mkdir -p 'apps'
touch 'apps/.keep'
mkdir -p 'arc'
touch 'arc/.keep'
mkdir -p 'archival'
touch 'archival/.keep'
mkdir -p 'archive'
touch 'archive/.keep'
mkdir -p 'archives'
touch 'archives/.keep'
mkdir -p 'arcs'
touch 'arcs/.keep'
mkdir -p 'article'
touch 'article/.keep'
mkdir -p 'articles'
touch 'articles/.keep'
mkdir -p 'asset'
touch 'asset/.keep'
mkdir -p 'assets'
touch 'assets/.keep'
mkdir -p 'aud'
touch 'aud/.keep'
mkdir -p 'audio'
touch 'audio/.keep'
mkdir -p 'audios'
touch 'audios/.keep'
mkdir -p 'auds'
touch 'auds/.keep'
mkdir -p 'aurelia_project'
touch 'aurelia_project/.keep'
mkdir -p 'auth'
touch 'auth/.keep'
mkdir -p 'authentication'
touch 'authentication/.keep'
mkdir -p 'auto'
touch 'auto/.keep'
mkdir -p 'aws'
touch 'aws/.keep'
mkdir -p 'azure-pipelines-ci'
touch 'azure-pipelines-ci/.keep'
mkdir -p 'azure-pipelines'
touch 'azure-pipelines/.keep'
mkdir -p 'back-up'
touch 'back-up/.keep'
mkdir -p 'back-ups'
touch 'back-ups/.keep'
mkdir -p 'backend'
touch 'backend/.keep'
mkdir -p 'backends'
touch 'backends/.keep'
mkdir -p 'backup'
touch 'backup/.keep'
mkdir -p 'backups'
touch 'backups/.keep'
mkdir -p 'bak'
touch 'bak/.keep'
mkdir -p 'baks'
touch 'baks/.keep'
mkdir -p 'base'
touch 'base/.keep'
mkdir -p 'bases'
touch 'bases/.keep'
mkdir -p 'batch'
touch 'batch/.keep'
mkdir -p 'batches'
touch 'batches/.keep'
mkdir -p 'batchs'
touch 'batchs/.keep'
mkdir -p 'benchmark'
touch 'benchmark/.keep'
mkdir -p 'benchmarks'
touch 'benchmarks/.keep'
mkdir -p 'bin'
touch 'bin/.keep'
mkdir -p 'bkp'
touch 'bkp/.keep'
mkdir -p 'bkps'
touch 'bkps/.keep'
mkdir -p 'bot'
touch 'bot/.keep'
mkdir -p 'bower_components'
touch 'bower_components/.keep'
mkdir -p 'browser'
touch 'browser/.keep'
mkdir -p 'browsers'
touch 'browsers/.keep'
mkdir -p 'build'
touch 'build/.keep'
mkdir -p 'buildkite'
touch 'buildkite/.keep'
mkdir -p 'bull'
touch 'bull/.keep'
mkdir -p 'cache'
touch 'cache/.keep'
mkdir -p 'cached'
touch 'cached/.keep'
mkdir -p 'calc'
touch 'calc/.keep'
mkdir -p 'calcs'
touch 'calcs/.keep'
mkdir -p 'calculation'
touch 'calculation/.keep'
mkdir -p 'calculations'
touch 'calculations/.keep'
mkdir -p 'cart'
touch 'cart/.keep'
mkdir -p 'cert'
touch 'cert/.keep'
mkdir -p 'certificate'
touch 'certificate/.keep'
mkdir -p 'certificates'
touch 'certificates/.keep'
mkdir -p 'certs'
touch 'certs/.keep'
mkdir -p 'cfg'
touch 'cfg/.keep'
mkdir -p 'cfgs'
touch 'cfgs/.keep'
mkdir -p 'cfn-gen'
touch 'cfn-gen/.keep'
mkdir -p 'changes'
touch 'changes/.keep'
mkdir -p 'changeset'
touch 'changeset/.keep'
mkdir -p 'changesets'
touch 'changesets/.keep'
mkdir -p 'chat'
touch 'chat/.keep'
mkdir -p 'chats'
touch 'chats/.keep'
mkdir -p 'ci'
touch 'ci/.keep'
mkdir -p 'circleci'
touch 'circleci/.keep'
mkdir -p 'class'
touch 'class/.keep'
mkdir -p 'classes'
touch 'classes/.keep'
mkdir -p 'cli'
touch 'cli/.keep'
mkdir -p 'client'
touch 'client/.keep'
mkdir -p 'clients'
touch 'clients/.keep'
mkdir -p 'clis'
touch 'clis/.keep'
mkdir -p 'cloudflare'
touch 'cloudflare/.keep'
mkdir -p 'cluster'
touch 'cluster/.keep'
mkdir -p 'clusters'
touch 'clusters/.keep'
mkdir -p 'cmd'
touch 'cmd/.keep'
mkdir -p 'cobol'
touch 'cobol/.keep'
mkdir -p 'code'
touch 'code/.keep'
mkdir -p 'color'
touch 'color/.keep'
mkdir -p 'colors'
touch 'colors/.keep'
mkdir -p 'command'
touch 'command/.keep'
mkdir -p 'commands'
touch 'commands/.keep'
mkdir -p 'common'
touch 'common/.keep'
mkdir -p 'components'
touch 'components/.keep'
mkdir -p 'concept'
touch 'concept/.keep'
mkdir -p 'concepts'
touch 'concepts/.keep'
mkdir -p 'conf'
touch 'conf/.keep'
mkdir -p 'config'
touch 'config/.keep'
mkdir -p 'configs'
touch 'configs/.keep'
mkdir -p 'configuration'
touch 'configuration/.keep'
mkdir -p 'configurations'
touch 'configurations/.keep'
mkdir -p 'confs'
touch 'confs/.keep'
mkdir -p 'connection'
touch 'connection/.keep'
mkdir -p 'connections'
touch 'connections/.keep'
mkdir -p 'console'
touch 'console/.keep'
mkdir -p 'constant'
touch 'constant/.keep'
mkdir -p 'constants'
touch 'constants/.keep'
mkdir -p 'container'
touch 'container/.keep'
mkdir -p 'containers'
touch 'containers/.keep'
mkdir -p 'content'
touch 'content/.keep'
mkdir -p 'contents'
touch 'contents/.keep'
mkdir -p 'context'
touch 'context/.keep'
mkdir -p 'contexts'
touch 'contexts/.keep'
mkdir -p 'contract-test'
touch 'contract-test/.keep'
mkdir -p 'contract-testing'
touch 'contract-testing/.keep'
mkdir -p 'contract-tests'
touch 'contract-tests/.keep'
mkdir -p 'contract'
touch 'contract/.keep'
mkdir -p 'contracts'
touch 'contracts/.keep'
mkdir -p 'controller'
touch 'controller/.keep'
mkdir -p 'controllers'
touch 'controllers/.keep'
mkdir -p 'conversation'
touch 'conversation/.keep'
mkdir -p 'conversations'
touch 'conversations/.keep'
mkdir -p 'core'
touch 'core/.keep'
mkdir -p 'coverage'
touch 'coverage/.keep'
mkdir -p 'crash'
touch 'crash/.keep'
mkdir -p 'crashes'
touch 'crashes/.keep'
mkdir -p 'css'
touch 'css/.keep'
mkdir -p 'custom'
touch 'custom/.keep'
mkdir -p 'customs'
touch 'customs/.keep'
mkdir -p 'cypress'
touch 'cypress/.keep'
mkdir -p 'data'
touch 'data/.keep'
mkdir -p 'database'
touch 'database/.keep'
mkdir -p 'databases'
touch 'databases/.keep'
mkdir -p 'db'
touch 'db/.keep'
mkdir -p 'debug'
touch 'debug/.keep'
mkdir -p 'debugging'
touch 'debugging/.keep'
mkdir -p 'decorator'
touch 'decorator/.keep'
mkdir -p 'decorators'
touch 'decorators/.keep'
mkdir -p 'delta'
touch 'delta/.keep'
mkdir -p 'deltas'
touch 'deltas/.keep'
mkdir -p 'demo'
touch 'demo/.keep'
mkdir -p 'demos'
touch 'demos/.keep'
mkdir -p 'design'
touch 'design/.keep'
mkdir -p 'designs'
touch 'designs/.keep'
mkdir -p 'desktop'
touch 'desktop/.keep'
mkdir -p 'devcontainer'
touch 'devcontainer/.keep'
mkdir -p 'directives'
touch 'directives/.keep'
mkdir -p 'dist'
touch 'dist/.keep'
mkdir -p 'doc'
touch 'doc/.keep'
mkdir -p 'docker'
touch 'docker/.keep'
mkdir -p 'dockerfiles'
touch 'dockerfiles/.keep'
mkdir -p 'docs'
touch 'docs/.keep'
mkdir -p 'document'
touch 'document/.keep'
mkdir -p 'documentation'
touch 'documentation/.keep'
mkdir -p 'documents'
touch 'documents/.keep'
mkdir -p 'download'
touch 'download/.keep'
mkdir -p 'downloads'
touch 'downloads/.keep'
mkdir -p 'draft'
touch 'draft/.keep'
mkdir -p 'drafts'
touch 'drafts/.keep'
mkdir -p 'DS_Store'
touch 'DS_Store/.keep'
mkdir -p 'dump'
touch 'dump/.keep'
mkdir -p 'dumps'
touch 'dumps/.keep'
mkdir -p 'e2e'
touch 'e2e/.keep'
mkdir -p 'effects'
touch 'effects/.keep'
mkdir -p 'email'
touch 'email/.keep'
mkdir -p 'emails'
touch 'emails/.keep'
mkdir -p 'entities'
touch 'entities/.keep'
mkdir -p 'enum'
touch 'enum/.keep'
mkdir -p 'enums'
touch 'enums/.keep'
mkdir -p 'env'
touch 'env/.keep'
mkdir -p 'environment'
touch 'environment/.keep'
mkdir -p 'environments'
touch 'environments/.keep'
mkdir -p 'envs'
touch 'envs/.keep'
mkdir -p 'err'
touch 'err/.keep'
mkdir -p 'error'
touch 'error/.keep'
mkdir -p 'errors'
touch 'errors/.keep'
mkdir -p 'errs'
touch 'errs/.keep'
mkdir -p 'etc'
touch 'etc/.keep'
mkdir -p 'event'
touch 'event/.keep'
mkdir -p 'events'
touch 'events/.keep'
mkdir -p 'example'
touch 'example/.keep'
mkdir -p 'examples'
touch 'examples/.keep'
mkdir -p 'expo-shared'
touch 'expo-shared/.keep'
mkdir -p 'expo'
touch 'expo/.keep'
mkdir -p 'export'
touch 'export/.keep'
mkdir -p 'exported'
touch 'exported/.keep'
mkdir -p 'exports'
touch 'exports/.keep'
mkdir -p 'extension'
touch 'extension/.keep'
mkdir -p 'extensions'
touch 'extensions/.keep'
mkdir -p 'extra'
touch 'extra/.keep'
mkdir -p 'extras'
touch 'extras/.keep'
mkdir -p 'fastlane'
touch 'fastlane/.keep'
mkdir -p 'fig'
touch 'fig/.keep'
mkdir -p 'figs'
touch 'figs/.keep'
mkdir -p 'figure'
touch 'figure/.keep'
mkdir -p 'figures'
touch 'figures/.keep'
mkdir -p 'firebase'
touch 'firebase/.keep'
mkdir -p 'fixture'
touch 'fixture/.keep'
mkdir -p 'fixtures'
touch 'fixtures/.keep'
mkdir -p 'flow-typed'
touch 'flow-typed/.keep'
mkdir -p 'font'
touch 'font/.keep'
mkdir -p 'fonts'
touch 'fonts/.keep'
mkdir -p 'forum'
touch 'forum/.keep'
mkdir -p 'fragments'
touch 'fragments/.keep'
mkdir -p 'frontend'
touch 'frontend/.keep'
mkdir -p 'frontends'
touch 'frontends/.keep'
mkdir -p 'func'
touch 'func/.keep'
mkdir -p 'funcs'
touch 'funcs/.keep'
mkdir -p 'function'
touch 'function/.keep'
mkdir -p 'functions'
touch 'functions/.keep'
mkdir -p 'gamemaker'
touch 'gamemaker/.keep'
mkdir -p 'gamemaker2'
touch 'gamemaker2/.keep'
mkdir -p 'gen'
touch 'gen/.keep'
mkdir -p 'generated'
touch 'generated/.keep'
mkdir -p 'generator'
touch 'generator/.keep'
mkdir -p 'generators'
touch 'generators/.keep'
mkdir -p 'gens'
touch 'gens/.keep'
mkdir -p 'git'
touch 'git/.keep'
mkdir -p 'githooks'
touch 'githooks/.keep'
mkdir -p 'github'
touch 'github/.keep'
mkdir -p 'gitlab'
touch 'gitlab/.keep'
mkdir -p 'global'
touch 'global/.keep'
mkdir -p 'glsl'
touch 'glsl/.keep'
mkdir -p 'godot-cpp'
touch 'godot-cpp/.keep'
mkdir -p 'godot'
touch 'godot/.keep'
mkdir -p 'gql'
touch 'gql/.keep'
mkdir -p 'gradle'
touch 'gradle/.keep'
mkdir -p 'graphql'
touch 'graphql/.keep'
mkdir -p 'guard'
touch 'guard/.keep'
mkdir -p 'guards'
touch 'guards/.keep'
mkdir -p 'gulp-tasks'
touch 'gulp-tasks/.keep'
mkdir -p 'gulp'
touch 'gulp/.keep'
mkdir -p 'gulpfile.babel.js'
touch 'gulpfile.babel.js/.keep'
mkdir -p 'gulpfile.js'
touch 'gulpfile.js/.keep'
mkdir -p 'gulpfile.mjs'
touch 'gulpfile.mjs/.keep'
mkdir -p 'gulpfile.ts'
touch 'gulpfile.ts/.keep'
mkdir -p 'handler'
touch 'handler/.keep'
mkdir -p 'handlers'
touch 'handlers/.keep'
mkdir -p 'helper'
touch 'helper/.keep'
mkdir -p 'helpers'
touch 'helpers/.keep'
mkdir -p 'hg'
touch 'hg/.keep'
mkdir -p 'hgext'
touch 'hgext/.keep'
mkdir -p 'hghooks'
touch 'hghooks/.keep'
mkdir -p 'histories'
touch 'histories/.keep'
mkdir -p 'history'
touch 'history/.keep'
mkdir -p 'hlsl'
touch 'hlsl/.keep'
mkdir -p 'home'
touch 'home/.keep'
mkdir -p 'hook'
touch 'hook/.keep'
mkdir -p 'hooks'
touch 'hooks/.keep'
mkdir -p 'html'
touch 'html/.keep'
mkdir -p 'husky'
touch 'husky/.keep'
mkdir -p 'i18n'
touch 'i18n/.keep'
mkdir -p 'ico'
touch 'ico/.keep'
mkdir -p 'icon'
touch 'icon/.keep'
mkdir -p 'icons'
touch 'icons/.keep'
mkdir -p 'icos'
touch 'icos/.keep'
mkdir -p 'idea'
touch 'idea/.keep'
mkdir -p 'image'
touch 'image/.keep'
mkdir -p 'images'
touch 'images/.keep'
mkdir -p 'img'
touch 'img/.keep'
mkdir -p 'imgs'
touch 'imgs/.keep'
mkdir -p 'import'
touch 'import/.keep'
mkdir -p 'imported'
touch 'imported/.keep'
mkdir -p 'imports'
touch 'imports/.keep'
mkdir -p 'inc'
touch 'inc/.keep'
mkdir -p 'include'
touch 'include/.keep'
mkdir -p 'includes'
touch 'includes/.keep'
mkdir -p 'integration-test'
touch 'integration-test/.keep'
mkdir -p 'integration-tests'
touch 'integration-tests/.keep'
mkdir -p 'integration'
touch 'integration/.keep'
mkdir -p 'integrations'
touch 'integrations/.keep'
mkdir -p 'interface'
touch 'interface/.keep'
mkdir -p 'interfaces'
touch 'interfaces/.keep'
mkdir -p 'internationalization'
touch 'internationalization/.keep'
mkdir -p 'ios'
touch 'ios/.keep'
mkdir -p 'it'
touch 'it/.keep'
mkdir -p 'j2'
touch 'j2/.keep'
mkdir -p 'java'
touch 'java/.keep'
mkdir -p 'javascript'
touch 'javascript/.keep'
mkdir -p 'javascripts'
touch 'javascripts/.keep'
mkdir -p 'jinja'
touch 'jinja/.keep'
mkdir -p 'jinja2'
touch 'jinja2/.keep'
mkdir -p 'job'
touch 'job/.keep'
mkdir -p 'jobs'
touch 'jobs/.keep'
mkdir -p 'js'
touch 'js/.keep'
mkdir -p 'json'
touch 'json/.keep'
mkdir -p 'jsons'
touch 'jsons/.keep'
mkdir -p 'jsx'
touch 'jsx/.keep'
mkdir -p 'jwt'
touch 'jwt/.keep'
mkdir -p 'k8s'
touch 'k8s/.keep'
mkdir -p 'key'
touch 'key/.keep'
mkdir -p 'keys'
touch 'keys/.keep'
mkdir -p 'kubernetes'
touch 'kubernetes/.keep'
mkdir -p 'l10n'
touch 'l10n/.keep'
mkdir -p 'lambda'
touch 'lambda/.keep'
mkdir -p 'lambdas'
touch 'lambdas/.keep'
mkdir -p 'lang'
touch 'lang/.keep'
mkdir -p 'langs'
touch 'langs/.keep'
mkdir -p 'language'
touch 'language/.keep'
mkdir -p 'languages'
touch 'languages/.keep'
mkdir -p 'layout'
touch 'layout/.keep'
mkdir -p 'layouts'
touch 'layouts/.keep'
mkdir -p 'less'
touch 'less/.keep'
mkdir -p 'lib'
touch 'lib/.keep'
mkdir -p 'libraries'
touch 'libraries/.keep'
mkdir -p 'library'
touch 'library/.keep'
mkdir -p 'libs'
touch 'libs/.keep'
mkdir -p 'linux'
touch 'linux/.keep'
mkdir -p 'linuxbsd'
touch 'linuxbsd/.keep'
mkdir -p 'locale'
touch 'locale/.keep'
mkdir -p 'locales'
touch 'locales/.keep'
mkdir -p 'localization'
touch 'localization/.keep'
mkdir -p 'log'
touch 'log/.keep'
mkdir -p 'logging'
touch 'logging/.keep'
mkdir -p 'logic'
touch 'logic/.keep'
mkdir -p 'logs'
touch 'logs/.keep'
mkdir -p 'lottie'
touch 'lottie/.keep'
mkdir -p 'lottiefiles'
touch 'lottiefiles/.keep'
mkdir -p 'lotties'
touch 'lotties/.keep'
mkdir -p 'lua'
touch 'lua/.keep'
mkdir -p 'mac'
touch 'mac/.keep'
mkdir -p 'macos'
touch 'macos/.keep'
mkdir -p 'mail'
touch 'mail/.keep'
mkdir -p 'mailers'
touch 'mailers/.keep'
mkdir -p 'mails'
touch 'mails/.keep'
mkdir -p 'manager'
touch 'manager/.keep'
mkdir -p 'managers'
touch 'managers/.keep'
mkdir -p 'mapping'
touch 'mapping/.keep'
mkdir -p 'mappings'
touch 'mappings/.keep'
mkdir -p 'markdown'
touch 'markdown/.keep'
mkdir -p 'math'
touch 'math/.keep'
mkdir -p 'maths'
touch 'maths/.keep'
mkdir -p 'md'
touch 'md/.keep'
mkdir -p 'measure'
touch 'measure/.keep'
mkdir -p 'measurement'
touch 'measurement/.keep'
mkdir -p 'measures'
touch 'measures/.keep'
mkdir -p 'messages'
touch 'messages/.keep'
mkdir -p 'messaging'
touch 'messaging/.keep'
mkdir -p 'META-INF'
touch 'META-INF/.keep'
mkdir -p 'meta'
touch 'meta/.keep'
mkdir -p 'middleware'
touch 'middleware/.keep'
mkdir -p 'middlewares'
touch 'middlewares/.keep'
mkdir -p 'misc'
touch 'misc/.keep'
mkdir -p 'miscellaneous'
touch 'miscellaneous/.keep'
mkdir -p 'mjml'
touch 'mjml/.keep'
mkdir -p 'mobile'
touch 'mobile/.keep'
mkdir -p 'mobiles'
touch 'mobiles/.keep'
mkdir -p 'mock'
touch 'mock/.keep'
mkdir -p 'mocks'
touch 'mocks/.keep'
mkdir -p 'mod'
touch 'mod/.keep'
mkdir -p 'modding'
touch 'modding/.keep'
mkdir -p 'model'
touch 'model/.keep'
mkdir -p 'models'
touch 'models/.keep'
mkdir -p 'moderator'
touch 'moderator/.keep'
mkdir -p 'moderators'
touch 'moderators/.keep'
mkdir -p 'mods'
touch 'mods/.keep'
mkdir -p 'module'
touch 'module/.keep'
mkdir -p 'modules'
touch 'modules/.keep'
mkdir -p 'mojo'
touch 'mojo/.keep'
mkdir -p 'moon'
touch 'moon/.keep'
mkdir -p 'movie'
touch 'movie/.keep'
mkdir -p 'movies'
touch 'movies/.keep'
mkdir -p 'mq'
touch 'mq/.keep'
mkdir -p 'music'
touch 'music/.keep'
mkdir -p 'netlify'
touch 'netlify/.keep'
mkdir -p 'next'
touch 'next/.keep'
mkdir -p 'node_modules'
touch 'node_modules/.keep'
mkdir -p 'now'
touch 'now/.keep'
mkdir -p 'nuxt'
touch 'nuxt/.keep'
mkdir -p 'nyc_output'
touch 'nyc_output/.keep'
mkdir -p 'nyc-output'
touch 'nyc-output/.keep'
mkdir -p 'option'
touch 'option/.keep'
mkdir -p 'options'
touch 'options/.keep'
mkdir -p 'other'
touch 'other/.keep'
mkdir -p 'others'
touch 'others/.keep'
mkdir -p 'out'
touch 'out/.keep'
mkdir -p 'package'
touch 'package/.keep'
mkdir -p 'packages'
touch 'packages/.keep'
mkdir -p 'pact'
touch 'pact/.keep'
mkdir -p 'pacts'
touch 'pacts/.keep'
mkdir -p 'page'
touch 'page/.keep'
mkdir -p 'pages'
touch 'pages/.keep'
mkdir -p 'partial'
touch 'partial/.keep'
mkdir -p 'partials'
touch 'partials/.keep'
mkdir -p 'patches'
touch 'patches/.keep'
mkdir -p 'pdf'
touch 'pdf/.keep'
mkdir -p 'pdfs'
touch 'pdfs/.keep'
mkdir -p 'pdm-build'
touch 'pdm-build/.keep'
mkdir -p 'pdm-plugins'
touch 'pdm-plugins/.keep'
mkdir -p 'performance'
touch 'performance/.keep'
mkdir -p 'photo'
touch 'photo/.keep'
mkdir -p 'photograph'
touch 'photograph/.keep'
mkdir -p 'photographs'
touch 'photographs/.keep'
mkdir -p 'photos'
touch 'photos/.keep'
mkdir -p 'php'
touch 'php/.keep'
mkdir -p 'phpmailer'
touch 'phpmailer/.keep'
mkdir -p 'pic'
touch 'pic/.keep'
mkdir -p 'pics'
touch 'pics/.keep'
mkdir -p 'picture'
touch 'picture/.keep'
mkdir -p 'pictures'
touch 'pictures/.keep'
mkdir -p 'pipe'
touch 'pipe/.keep'
mkdir -p 'pipes'
touch 'pipes/.keep'
mkdir -p 'pkg'
touch 'pkg/.keep'
mkdir -p 'pkgs'
touch 'pkgs/.keep'
mkdir -p 'plastic'
touch 'plastic/.keep'
mkdir -p 'plugin'
touch 'plugin/.keep'
mkdir -p 'plugins'
touch 'plugins/.keep'
mkdir -p 'portability'
touch 'portability/.keep'
mkdir -p 'portable'
touch 'portable/.keep'
mkdir -p 'post'
touch 'post/.keep'
mkdir -p 'posts'
touch 'posts/.keep'
mkdir -p 'prisma'
touch 'prisma/.keep'
mkdir -p 'private'
touch 'private/.keep'
mkdir -p 'project'
touch 'project/.keep'
mkdir -p 'projects'
touch 'projects/.keep'
mkdir -p 'proto'
touch 'proto/.keep'
mkdir -p 'protobuf'
touch 'protobuf/.keep'
mkdir -p 'protobufs'
touch 'protobufs/.keep'
mkdir -p 'protos'
touch 'protos/.keep'
mkdir -p 'provider'
touch 'provider/.keep'
mkdir -p 'providers'
touch 'providers/.keep'
mkdir -p 'public_html'
touch 'public_html/.keep'
mkdir -p 'public'
touch 'public/.keep'
mkdir -p 'pwa'
touch 'pwa/.keep'
mkdir -p 'pycache'
touch 'pycache/.keep'
mkdir -p 'pytest_cache'
touch 'pytest_cache/.keep'
mkdir -p 'python'
touch 'python/.keep'
mkdir -p 'quasar'
touch 'quasar/.keep'
mkdir -p 'queue'
touch 'queue/.keep'
mkdir -p 'queues'
touch 'queues/.keep'
mkdir -p 'react'
touch 'react/.keep'
mkdir -p 'reactjs'
touch 'reactjs/.keep'
mkdir -p 'reducer'
touch 'reducer/.keep'
mkdir -p 'reducers'
touch 'reducers/.keep'
mkdir -p 'release'
touch 'release/.keep'
mkdir -p 'report'
touch 'report/.keep'
mkdir -p 'reports'
touch 'reports/.keep'
mkdir -p 'res'
touch 'res/.keep'
mkdir -p 'resolver'
touch 'resolver/.keep'
mkdir -p 'resolvers'
touch 'resolvers/.keep'
mkdir -p 'resource'
touch 'resource/.keep'
mkdir -p 'resources'
touch 'resources/.keep'
mkdir -p 'restapi'
touch 'restapi/.keep'
mkdir -p 'review'
touch 'review/.keep'
mkdir -p 'reviewed'
touch 'reviewed/.keep'
mkdir -p 'reviews'
touch 'reviews/.keep'
mkdir -p 'revisal'
touch 'revisal/.keep'
mkdir -p 'revisals'
touch 'revisals/.keep'
mkdir -p 'robot'
touch 'robot/.keep'
mkdir -p 'router'
touch 'router/.keep'
mkdir -p 'routers'
touch 'routers/.keep'
mkdir -p 'routes'
touch 'routes/.keep'
mkdir -p 'rule'
touch 'rule/.keep'
mkdir -p 'rules'
touch 'rules/.keep'
mkdir -p 'sample-data'
touch 'sample-data/.keep'
mkdir -p 'sample'
touch 'sample/.keep'
mkdir -p 'samples'
touch 'samples/.keep'
mkdir -p 'sass'
touch 'sass/.keep'
mkdir -p 'scala'
touch 'scala/.keep'
mkdir -p 'schema'
touch 'schema/.keep'
mkdir -p 'schemas'
touch 'schemas/.keep'
mkdir -p 'screen'
touch 'screen/.keep'
mkdir -p 'screengrab'
touch 'screengrab/.keep'
mkdir -p 'screengrabs'
touch 'screengrabs/.keep'
mkdir -p 'screens'
touch 'screens/.keep'
mkdir -p 'screenshot'
touch 'screenshot/.keep'
mkdir -p 'screenshots'
touch 'screenshots/.keep'
mkdir -p 'script'
touch 'script/.keep'
mkdir -p 'scripting'
touch 'scripting/.keep'
mkdir -p 'scripts'
touch 'scripts/.keep'
mkdir -p 'scss'
touch 'scss/.keep'
mkdir -p 'secret'
touch 'secret/.keep'
mkdir -p 'secrets'
touch 'secrets/.keep'
mkdir -p 'secure'
touch 'secure/.keep'
mkdir -p 'security'
touch 'security/.keep'
mkdir -p 'seed'
touch 'seed/.keep'
mkdir -p 'seeders'
touch 'seeders/.keep'
mkdir -p 'seeding'
touch 'seeding/.keep'
mkdir -p 'seeds'
touch 'seeds/.keep'
mkdir -p 'selector'
touch 'selector/.keep'
mkdir -p 'selectors'
touch 'selectors/.keep'
mkdir -p 'server'
touch 'server/.keep'
mkdir -p 'serverless'
touch 'serverless/.keep'
mkdir -p 'servers'
touch 'servers/.keep'
mkdir -p 'service'
touch 'service/.keep'
mkdir -p 'services'
touch 'services/.keep'
mkdir -p 'setting'
touch 'setting/.keep'
mkdir -p 'settings'
touch 'settings/.keep'
mkdir -p 'shader'
touch 'shader/.keep'
mkdir -p 'shaders'
touch 'shaders/.keep'
mkdir -p 'shared'
touch 'shared/.keep'
mkdir -p 'shop'
touch 'shop/.keep'
mkdir -p 'shopping-cart'
touch 'shopping-cart/.keep'
mkdir -p 'shopping'
touch 'shopping/.keep'
mkdir -p 'site'
touch 'site/.keep'
mkdir -p 'sketch'
touch 'sketch/.keep'
mkdir -p 'sketches'
touch 'sketches/.keep'
mkdir -p 'smtp'
touch 'smtp/.keep'
mkdir -p 'snapshots'
touch 'snapshots/.keep'
mkdir -p 'sound'
touch 'sound/.keep'
mkdir -p 'sounds'
touch 'sounds/.keep'
mkdir -p 'source'
touch 'source/.keep'
mkdir -p 'sources'
touch 'sources/.keep'
mkdir -p 'spec'
touch 'spec/.keep'
mkdir -p 'specs'
touch 'specs/.keep'
mkdir -p 'spellcheck'
touch 'spellcheck/.keep'
mkdir -p 'sql'
touch 'sql/.keep'
mkdir -p 'src'
touch 'src/.keep'
mkdir -p 'srcs'
touch 'srcs/.keep'
mkdir -p 'ssl'
touch 'ssl/.keep'
mkdir -p 'stack'
touch 'stack/.keep'
mkdir -p 'stacks'
touch 'stacks/.keep'
mkdir -p 'start'
touch 'start/.keep'
mkdir -p 'state'
touch 'state/.keep'
mkdir -p 'states'
touch 'states/.keep'
mkdir -p 'static'
touch 'static/.keep'
mkdir -p 'stencil'
touch 'stencil/.keep'
mkdir -p 'store'
touch 'store/.keep'
mkdir -p 'stores'
touch 'stores/.keep'
mkdir -p 'stories'
touch 'stories/.keep'
mkdir -p 'storybook'
touch 'storybook/.keep'
mkdir -p 'style'
touch 'style/.keep'
mkdir -p 'styles'
touch 'styles/.keep'
mkdir -p 'stylesheet'
touch 'stylesheet/.keep'
mkdir -p 'stylesheets'
touch 'stylesheets/.keep'
mkdir -p 'stylus'
touch 'stylus/.keep'
mkdir -p 'sublime'
touch 'sublime/.keep'
mkdir -p 'submodules'
touch 'submodules/.keep'
mkdir -p 'supabase'
touch 'supabase/.keep'
mkdir -p 'svelte-kit'
touch 'svelte-kit/.keep'
mkdir -p 'svelte'
touch 'svelte/.keep'
mkdir -p 'svg'
touch 'svg/.keep'
mkdir -p 'svgs'
touch 'svgs/.keep'
mkdir -p 'syntax'
touch 'syntax/.keep'
mkdir -p 'syntaxes'
touch 'syntaxes/.keep'
mkdir -p 'target'
touch 'target/.keep'
mkdir -p 'taskfile'
touch 'taskfile/.keep'
mkdir -p 'taskfiles'
touch 'taskfiles/.keep'
mkdir -p 'tasks'
touch 'tasks/.keep'
mkdir -p 'television'
touch 'television/.keep'
mkdir -p 'temp'
touch 'temp/.keep'
mkdir -p 'template'
touch 'template/.keep'
mkdir -p 'templates'
touch 'templates/.keep'
mkdir -p 'terraform'
touch 'terraform/.keep'
mkdir -p 'test'
touch 'test/.keep'
mkdir -p 'testing'
touch 'testing/.keep'
mkdir -p 'tests'
touch 'tests/.keep'
mkdir -p 'theme'
touch 'theme/.keep'
mkdir -p 'themes'
touch 'themes/.keep'
mkdir -p 'third-party'
touch 'third-party/.keep'
mkdir -p 'tickets'
touch 'tickets/.keep'
mkdir -p 'tmp'
touch 'tmp/.keep'
mkdir -p 'token'
touch 'token/.keep'
mkdir -p 'tokens'
touch 'tokens/.keep'
mkdir -p 'toolbox'
touch 'toolbox/.keep'
mkdir -p 'toolboxes'
touch 'toolboxes/.keep'
mkdir -p 'tooling'
touch 'tooling/.keep'
mkdir -p 'toolkit'
touch 'toolkit/.keep'
mkdir -p 'toolkits'
touch 'toolkits/.keep'
mkdir -p 'tools'
touch 'tools/.keep'
mkdir -p 'translate'
touch 'translate/.keep'
mkdir -p 'translation'
touch 'translation/.keep'
mkdir -p 'translations'
touch 'translations/.keep'
mkdir -p 'trigger'
touch 'trigger/.keep'
mkdir -p 'triggers'
touch 'triggers/.keep'
mkdir -p 'ts'
touch 'ts/.keep'
mkdir -p 'tv'
touch 'tv/.keep'
mkdir -p 'tx'
touch 'tx/.keep'
mkdir -p 'types'
touch 'types/.keep'
mkdir -p 'typescript'
touch 'typescript/.keep'
mkdir -p 'typings'
touch 'typings/.keep'
mkdir -p 'unity'
touch 'unity/.keep'
mkdir -p 'unix'
touch 'unix/.keep'
mkdir -p 'update'
touch 'update/.keep'
mkdir -p 'updates'
touch 'updates/.keep'
mkdir -p 'upgrade'
touch 'upgrade/.keep'
mkdir -p 'upgrades'
touch 'upgrades/.keep'
mkdir -p 'upload'
touch 'upload/.keep'
mkdir -p 'uploads'
touch 'uploads/.keep'
mkdir -p 'util'
touch 'util/.keep'
mkdir -p 'utilities'
touch 'utilities/.keep'
mkdir -p 'utility'
touch 'utility/.keep'
mkdir -p 'utils'
touch 'utils/.keep'
mkdir -p 'validation'
touch 'validation/.keep'
mkdir -p 'validations'
touch 'validations/.keep'
mkdir -p 'validator'
touch 'validator/.keep'
mkdir -p 'validators'
touch 'validators/.keep'
mkdir -p 'vendor'
touch 'vendor/.keep'
mkdir -p 'vendors'
touch 'vendors/.keep'
mkdir -p 'venv'
touch 'venv/.keep'
mkdir -p 'vercel'
touch 'vercel/.keep'
mkdir -p 'verdaccio'
touch 'verdaccio/.keep'
mkdir -p 'vid'
touch 'vid/.keep'
mkdir -p 'video'
touch 'video/.keep'
mkdir -p 'videos'
touch 'videos/.keep'
mkdir -p 'vids'
touch 'vids/.keep'
mkdir -p 'view'
touch 'view/.keep'
mkdir -p 'views'
touch 'views/.keep'
mkdir -p 'vm'
touch 'vm/.keep'
mkdir -p 'vms'
touch 'vms/.keep'
mkdir -p 'vscode-test'
touch 'vscode-test/.keep'
mkdir -p 'vscode'
touch 'vscode/.keep'
mkdir -p 'vue'
touch 'vue/.keep'
mkdir -p 'vuepress'
touch 'vuepress/.keep'
mkdir -p 'wakatime'
touch 'wakatime/.keep'
mkdir -p 'web'
touch 'web/.keep'
mkdir -p 'webpack'
touch 'webpack/.keep'
mkdir -p 'website'
touch 'website/.keep'
mkdir -p 'widget'
touch 'widget/.keep'
mkdir -p 'widgets'
touch 'widgets/.keep'
mkdir -p 'win'
touch 'win/.keep'
mkdir -p 'windows'
touch 'windows/.keep'
mkdir -p 'wordpress-org'
touch 'wordpress-org/.keep'
mkdir -p 'wp-content'
touch 'wp-content/.keep'
mkdir -p 'www'
touch 'www/.keep'
mkdir -p 'wwwroot'
touch 'wwwroot/.keep'
mkdir -p 'yarn'
touch 'yarn/.keep'
